#   "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDg3OTFlZjEzYjgyYTg5Y2Y5OTVjZCIsImlhdCI6MTcxNjAyNTYzMH0.NgA-VBocAxXo4Az8bweZI_RviiDNUWMhUKVP-l4Sd20"

# POST http://localhost:3000/create-blog
# Content-Type: application/json

# {
#     "fullname":"spiderman",
#     "email":"spider@gmail.com",
#     "password":"Spider123"
# }
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODY1ODNiN2YyODYxMGZjNjdiYzQ5MSIsImlhdCI6MTcyMDA4MDQ5MH0.gCWZAUXR1j843nebkreSyZXmmFcPfEYln2Be4fZbnTI


POST   http://localhost:3000/change-password
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODY1ODNiN2YyODYxMGZjNjdiYzQ5MSIsImlhdCI6MTcyMDA4MDQ5MH0.gCWZAUXR1j843nebkreSyZXmmFcPfEYln2Be4fZbnTI

{
    "currentPassword":"WayBackHome@1",
    "newPassword":"WayBackHome@2"
}

# POST   http://localhost:3000/get-profile
# Content-Type:application/json 

# {
#     "name":"mahadali9927"
# }